// web-react/src/pages/InformacoesGerais.js
import React, { Component } from 'react'
import { Link } from 'react-router-dom'
import {
    Button,
    Header,
    Image,
    Menu,
    Table,
    Modal,
    Form,
    Message,
    Popup
} from 'semantic-ui-react'

import {
    DateInput,
} from 'semantic-ui-calendar-react';

import 'semantic-ui-css/semantic.min.css'
import '../App.css'
import InforamcoesGeraisService from '../services/InformacoesGeraisService'

const informacoesGeraisService = new InforamcoesGeraisService()

class InformacoesGerais extends Component {

    constructor(props) {
        super(props);
        this.state = { selectedInformacoesGerais: {} };
    }

    closeModal = () => {
        this.setState({
            openModal: false,
            selectedInformacoesGerais: {
            }
        })
    }

    save = () => {
        if (this.state.hasOwnProperty('selectedInformacoesGerais')) {
            informacoesGeraisService.save(this.state.selectedInformacoesGerais, (response) => {
                this.closeModal()
                this.loadContent()
            }, (error) => {
                console.log(error)
            })
        }
    }

    openinformacoesGerais = (informacoesGerais, event) => {
        console.log(informacoesGerais)
        this.setState({
            openModal: true,
            selectedInformacoesGerais: informacoesGerais
        })
    }

    newinformacoesGerais = (event) => {
        this.setState({
            openModal: true,
            selectedInformacoesGerais: {
            }
        })
    }

    loadContent = () => {
        informacoesGeraisService.listAll(response => {
            this.setState({ listaInformacoesGerais: response.data })
        }, () => { }, () => { })
    }

    componentWillMount = () => {
        this.loadContent()
    }

    updateselectedInformacoesGerais = (event, { name, value }) => {
        console.log(name, value);
        if (this.state.hasOwnProperty('selectedInformacoesGerais')) {
            var selectedInformacoesGerais = this.state.selectedInformacoesGerais
            selectedInformacoesGerais[name] = value
            this.setState({
                selectedInformacoesGerais: selectedInformacoesGerais
            })
        }
    }


    render() {
        return (
            <div className='container'>
                <header>
                    <div className='header-content'>
                        <Image src={require('../assets/logomarcaPontoSistemas.png')} size='small' centered/>
                        {/* <Button primary floated='right' as={Link} to='/'>Ofertas</Button> */}
                    </div>
                </header>
                <main>
                    <br />
                    <Menu>
                        <Menu.Item primary onClick={this.newinformacoesGerais.bind(this)} content="Adicionar" />
                    </Menu>
                    <div>
                        <Table striped selectable basic='very'>
                            <Table.Header>
                                <Table.Row>
                                    <Table.HeaderCell>Código</Table.HeaderCell>
                                    <Table.HeaderCell>Razão Social</Table.HeaderCell>
                                    <Table.HeaderCell>Endereço</Table.HeaderCell>
                                    <Table.HeaderCell>Bairro</Table.HeaderCell>
                                    <Table.HeaderCell>Número</Table.HeaderCell>
                                    <Table.HeaderCell>Cidade</Table.HeaderCell>
                                    <Table.HeaderCell>UF</Table.HeaderCell>
                                    <Table.HeaderCell>CNPJ</Table.HeaderCell>
                                    <Table.HeaderCell>Percentual Multa</Table.HeaderCell>
                                    <Table.HeaderCell>Percentual Desconto</Table.HeaderCell>
                                    <Table.HeaderCell>Percentual Juros</Table.HeaderCell>
                                </Table.Row>
                            </Table.Header>

                            <Table.Body>
                                {this.state.listaInformacoesGerais && this.state.listaInformacoesGerais.map((informacoesGerais, index) =>
                                    <Popup trigger={
                                        <Table.Row onClick={this.openinformacoesGerais.bind(this, informacoesGerais)}>
                                            <Table.Cell>{informacoesGerais.codigoEmpresa}</Table.Cell>
                                            <Table.Cell>{informacoesGerais.razaoSocial}</Table.Cell>
                                            <Table.Cell>{informacoesGerais.endereco}</Table.Cell>
                                            <Table.Cell>{informacoesGerais.bairro}</Table.Cell>
                                            <Table.Cell>{informacoesGerais.numero}</Table.Cell>
                                            <Table.Cell>{informacoesGerais.cidade}</Table.Cell>
                                            <Table.Cell>{informacoesGerais.uf}</Table.Cell>
                                            <Table.Cell>{informacoesGerais.cnpj}</Table.Cell>
                                            <Table.Cell>{informacoesGerais.percMulta}</Table.Cell>
                                            <Table.Cell>{informacoesGerais.percDesconto}</Table.Cell>
                                            <Table.Cell>{informacoesGerais.percJuros}</Table.Cell>
                                        </Table.Row>
                                    } content='Clique para editar' key={index} />
                                )}
                            </Table.Body>
                        </Table>
                    </div>
                    <Modal open={this.state.openModal} >
                        <Modal.Header>{this.state.selectedInformacoesGerais ? this.state.selectedInformacoesGerais.title : 'Novo    '}</Modal.Header>
                        <Modal.Content scrolling>
                            <Message positive color='red' error hidden={!this.state.errorMessage}>
                                <Message.Header>Algo de errado aconteceu :(</Message.Header>
                                <p>
                                    {this.state.errorMessage}
                                </p>
                            </Message>
                            <Form unstackable>
                                <Form.Input
                                    name='razaoSocial'
                                    label='Razão Social'
                                    placeholder='Razão Social'
                                    value={this.state.selectedInformacoesGerais.razaoSocial}
                                    onChange={this.updateselectedInformacoesGerais} />

                                <Form.Input
                                    name='endereco'
                                    label='Endereço'
                                    placeholder='Endereço'
                                    value={this.state.selectedInformacoesGerais.endereco}
                                    onChange={this.updateselectedInformacoesGerais} />

                                <Form.Input
                                    name='bairro'
                                    label='Bairro'
                                    placeholder='Bairro'
                                    value={this.state.selectedInformacoesGerais.bairro}
                                    onChange={this.updateselectedInformacoesGerais} />

                                <Form.Input
                                    name='numero'
                                    label='Número'
                                    placeholder='Número'
                                    value={this.state.selectedInformacoesGerais.numero}
                                    onChange={this.updateselectedInformacoesGerais} />

                                <Form.Input
                                    name='cidade'
                                    label='Cidade'
                                    placeholder='Cidade'
                                    value={this.state.selectedInformacoesGerais.cidade}
                                    onChange={this.updateselectedInformacoesGerais} />

                                <Form.Input
                                    name='uf'
                                    label='UF'
                                    placeholder='UF'
                                    value={this.state.selectedInformacoesGerais.uf}
                                    onChange={this.updateselectedInformacoesGerais} />

                                <Form.Input
                                    name='cnpj'
                                    label='cnpj'
                                    placeholder='cnpj'
                                    value={this.state.selectedInformacoesGerais.cnpj}
                                    onChange={this.updateselectedInformacoesGerais} />

                                <Form.Input
                                    name='percMulta'
                                    label='Percentual Multa'
                                    placeholder='Percentual Multa'
                                    value={this.state.selectedInformacoesGerais.percMulta}
                                    onChange={this.updateselectedInformacoesGerais} />

                                <Form.Input
                                    name='percDesconto'
                                    label='Percentual Desconto'
                                    placeholder='Percentual Desconto'
                                    value={this.state.selectedInformacoesGerais.percDesconto}
                                    onChange={this.updateselectedInformacoesGerais} />

                                <Form.Input
                                    name='percJuros'
                                    label='Percentual Juros'
                                    placeholder='Percentual Juros'
                                    value={this.state.selectedInformacoesGerais.percJuros}
                                    onChange={this.updateselectedInformacoesGerais} />
                            </Form>
                        </Modal.Content>
                        <Modal.Actions>
                            <Button onClick={this.closeModal} negative>Cancelar</Button>
                            <Button onClick={this.save} positive>Salvar</Button>
                        </Modal.Actions>
                    </Modal>
                </main>
                {/* <footer> <Header size='small' color='black'>Desenvolvido por <a href='http://cleitoncardoso.github.io/' target='_blank' rel='noopener noreferrer'>Cleiton Cardoso </a></Header></footer> */}
            </div>
        );
    }
}

export default InformacoesGerais;

// web-vue/src/pages/InformacoesGerais.vue
<template>
  <div class="container">
    <header>
      <div class="header-content">
        <img
          alt="Vue logo"
          src="../assets/logomarcaPontoSistemas.png"
          class="ui small centered image"
        >
        <!-- <sui-image src="../assets/logo.png" size="small" centered/> -->
        <!-- <sui-button floated="left" content="Left floated" /> -->
      </div>
    </header>
    <main>
      <br>
      <!-- MENU  -->
      <sui-menu>
        <sui-menu-item link name="adicionar" @click.native="openModal">Adicionar</sui-menu-item>
      </sui-menu>
      <div>
        <!-- TABLE -->
        <sui-table basic="very" striped>
          <sui-table-header>
            <sui-table-row>
              <sui-table-header-cell>Código</sui-table-header-cell>
              <sui-table-header-cell>Razão Social</sui-table-header-cell>
              <sui-table-header-cell>Endereço</sui-table-header-cell>
              <sui-table-header-cell>Bairro</sui-table-header-cell>
              <sui-table-header-cell>Número</sui-table-header-cell>
              <sui-table-header-cell>Cidade</sui-table-header-cell>
              <sui-table-header-cell>UF</sui-table-header-cell>
              <sui-table-header-cell>CNPJ</sui-table-header-cell>
              <sui-table-header-cell>Percentual Multa</sui-table-header-cell>
              <sui-table-header-cell>Percentual Desconto</sui-table-header-cell>
              <sui-table-header-cell>Percentual Juros</sui-table-header-cell>
            </sui-table-row>
          </sui-table-header>
          <sui-table-body>
            <sui-table-row
              v-for="informacoesGerais in this.listaInformacoesGerais"
              v-bind:key="informacoesGerais.codigoEmpresa"
            >
              <sui-table-cell>{{informacoesGerais.codigoEmpresa}}</sui-table-cell>
              <sui-table-cell>{{informacoesGerais.razaoSocial}}</sui-table-cell>
              <sui-table-cell>{{informacoesGerais.endereco}}</sui-table-cell>
              <sui-table-cell>{{informacoesGerais.bairro}}</sui-table-cell>
              <sui-table-cell>{{informacoesGerais.numero}}</sui-table-cell>
              <sui-table-cell>{{informacoesGerais.cidade}}</sui-table-cell>
              <sui-table-cell>{{informacoesGerais.uf}}</sui-table-cell>
              <sui-table-cell>{{informacoesGerais.cnpj}}</sui-table-cell>
              <sui-table-cell>{{informacoesGerais.percMulta}}</sui-table-cell>
              <sui-table-cell>{{informacoesGerais.percDesconto}}</sui-table-cell>
              <sui-table-cell>{{informacoesGerais.percJuros}}</sui-table-cell>
            </sui-table-row>
          </sui-table-body>
        </sui-table>
      </div>
      <!-- MODAL -->

      <sui-modal v-model="open">
        <sui-modal-content scrolling>
          <sui-form>
            <sui-form-field>
              <label>Razão Social</label>
              <input placeholder="Razão Social" v-model="selectedInformacoesGerais.razaoSocial">
            </sui-form-field>
            <sui-form-field>
              <label>Endereço</label>
              <input placeholder="Endereço" v-model="selectedInformacoesGerais.endereco">
            </sui-form-field>
            <sui-form-field>
              <label>Bairro</label>
              <input placeholder="Bairro" v-model="selectedInformacoesGerais.bairro">
            </sui-form-field>
            <sui-form-field>
              <label>Número</label>
              <input placeholder="Número" type="number" v-model="selectedInformacoesGerais.numero">
            </sui-form-field>
            <sui-form-field>
              <label>Cidade</label>
              <input placeholder="Cidade" v-model="selectedInformacoesGerais.cidade">
            </sui-form-field>
            <sui-form-field>
              <label>UF</label>
              <input placeholder="UF" v-model="selectedInformacoesGerais.uf">
            </sui-form-field>
            <sui-form-field>
              <label>CNPJ</label>
              <input placeholder="CNPJ" v-model="selectedInformacoesGerais.cnpj">
            </sui-form-field>
            <sui-form-field>
              <label>Percentual Multa</label>
              <input
                placeholder="Percentual Multa"
                type="number"
                v-model="selectedInformacoesGerais.percMulta"
              >
            </sui-form-field>
            <sui-form-field>
              <label>Percentual Desconto</label>
              <input
                placeholder="Percentual Desconto"
                type="number"
                v-model="selectedInformacoesGerais.percDesconto"
              >
            </sui-form-field>
            <sui-form-field>
              <label>Percentual Juros</label>
              <input
                placeholder="Percentual Juros"
                type="number"
                v-model="selectedInformacoesGerais.percJuros"
              >
            </sui-form-field>
          </sui-form>
        </sui-modal-content>
        <sui-modal-actions>
          <sui-button negative @click.native="closeModal">cancelar</sui-button>
          <sui-button positive @click.native="salvar">Salvar</sui-button>
        </sui-modal-actions>
      </sui-modal>
    </main>
    <!-- {/* <footer> <Header size='small' color='black'>Desenvolvido por <a href='http://cleitoncardoso.github.io/' target='_blank' rel='noopener noreferrer'>Cleiton Cardoso </a></Header></footer> */} -->
  </div>
</template>

<script type = "text/javascript" >
import InformacoesGeraisService from "../services/InformacoesGeraisService.js";

const informacoesGeraisService = new InformacoesGeraisService();

export default {
  data: function() {
    return {
      listaInformacoesGerais: [],
      open: false,
      selectedInformacoesGerais: {}
    };
  },
  created: function() {
    this.loadData();
  },
  methods: {
    loadData: function() {
      informacoesGeraisService.listAll(
        response => {
          this.listaInformacoesGerais = response.data;
        },
        () => {},
        () => {}
      );
    },
    openModal: function() {
      this.open = true;
    },
    closeModal: function() {
      this.open = false;
    },
    salvar: function() {
      informacoesGeraisService.save(
        this.selectedInformacoesGerais,
        response => {
          this.selectedInformacoesGerais = {};
          this.loadData();
          this.closeModal();
        },
        error => {
          console.log(error);
        }
      );
    }
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
